export {default as NavBar} from './Navbar/Navbar'
export {default as Header} from './Header/Header'
export {default as Info} from './Info/Info'
export {default as Projects} from './Projects/Projects'
export {default as Skills} from './Skills/Skills'
export {default as Tools} from './Tools/Tools'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'